jrl-mathtools: jrlMathTools::Angle Class Reference
jrlMathTools::Angle Class Reference
This class implements simple computations on angles.
#include </home/thomas/profiles/laas/src/unstable/jrl/jrl-mathtools/include/jrl/mathtools/angle.hh>
Public Member Functions
Angle ()
Angle (const double &angle)
Angle (const Angle &angle)
Copy Constructor.
const double & value () const
Angle value.
operator const double & () const
Cast into a double.
const double & operator= (const double &value)
Operator = with a double.
Angle operator- (const Angle &angle) const
Difference between two angles.
Angle operator+ (const Angle &angle) const
Sum of two angles.
Angle operator* (const double &coef)
Multiplication of an angle by a real number.
Angle interpolate (const double &alpha, const Angle &angle) const
Interpolation between two angles.
std::ostream & display (std::ostream &os) const
output to a stream.
double distance (const Angle &angle) const
Distance on unit circle.
Protected Member Functions
void setBetweenMinusAndPlusPI ()
Set angle between -PI and PI.
Protected Attributes
double attAngle
angular value.
Detailed Description
This class implements simple computations on angles.
Constructor & Destructor Documentation
jrlMathTools::Angle::Angle () [inline]
Referenced by interpolate(), operator*(), operator+(), and operator-().
jrlMathTools::Angle::Angle (const double & angle) [inline]
References setBetweenMinusAndPlusPI().
jrlMathTools::Angle::Angle (const Angle & angle) [inline]
Copy Constructor.
Member Function Documentation
std::ostream& jrlMathTools::Angle::display (std::ostream & os) const [inline]
output to a stream.
References attAngle.
Referenced by jrlMathTools::display().
double jrlMathTools::Angle::distance (const Angle & angle) const [inline]
Distance on unit circle.
References attAngle.
Angle jrlMathTools::Angle::interpolate (const double & alpha, const Angle & angle) const [inline]
Interpolation between two angles.
Parameters:
alpha interpolation parameter between 0 and 1.
angle second angle of interpolation.
Returns:
an angle between this one and angle along the shortest arc.
if alpha = 0, return this angle,
if alpha = 1, return angle.
References Angle(), and attAngle.
jrlMathTools::Angle::operator const double & () const [inline]
Cast into a double.
References attAngle.
Angle jrlMathTools::Angle::operator* (const double & coef) [inline]
Multiplication of an angle by a real number.
References Angle(), and attAngle.
Angle jrlMathTools::Angle::operator+ (const Angle & angle) const [inline]
Sum of two angles.
References Angle(), and attAngle.
Angle jrlMathTools::Angle::operator- (const Angle & angle) const [inline]
Difference between two angles.
References Angle(), and attAngle.
const double& jrlMathTools::Angle::operator= (const double & value) [inline]
Operator = with a double.
References attAngle, and setBetweenMinusAndPlusPI().
void jrlMathTools::Angle::setBetweenMinusAndPlusPI () [inline, protected]
Set angle between -PI and PI.
References attAngle.
Referenced by Angle(), and operator=().
const double& jrlMathTools::Angle::value () const [inline]
Angle value.
References attAngle.
Referenced by jrlMathTools::cos(), jrlMathTools::operator*(), jrlMathTools::sin(), and jrlMathTools::tan().
Member Data Documentation
double jrlMathTools::Angle::attAngle [protected]
angular value.
Referenced by display(), distance(), interpolate(), operator const double &(), operator*(), operator+(), operator-(), operator=(), setBetweenMinusAndPlusPI(), and value().
jrl-mathtools library documentation